### ISSUE TITLE
STOP THIS!

### ISSUE THREAD

**Issue by Max2288** [siriusdevs/rpm_chat_2023#1]
![изображение](https://user-images.githubusercontent.com/42071821/219662544-f3c28697-2a59-4c66-bab4-f59bc6bd2b0b.png)

**Comment by siriusdevs** [comment]
![Screenshot from 2023-02-18 11-40-45](https://user-images.githubusercontent.com/102812997/219850858-bd40871a-7ffd-418c-81ae-ebc71b850e03.png)
@Max2288 get rekt
